---

- hosts: "{{ host_list }}"
  gather_facts: False

  tasks:
  - name: Set authorized key for "{{ remote_user }}" copying it from current "{{ remote_user }}"
    authorized_key:
      user: "{{ remote_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      # key: "ssh-rsa AAAAB3NzaC..."
      validate_certs: no
      exclusive: False
